### ISSUE TITLE
php-fpm problem

### ISSUE THREAD

**Issue by riffleRock** [ShVerni/AirBeamLogger#1]
The line:

sudo apt-get install nginx php-fpm hostapd isc-dhcp-server python3-serial

returned an error that couldn't locate php-fpm.  I substituted php5-fpm and it worked.  Is php-fpm supposed to still be available?  Did I do something wrong?

**Comment by ShVerni** [comment]
Hello,

I'm not sure why you're seeing that error, I just checked and php-fpm does appear to be available in the standard Raspbian repositories (see the below screenshot). Are you using an up-to-date version of Raspbian? 
![pi](https://user-images.githubusercontent.com/15352177/42400995-9fac760e-8141-11e8-83dc-04e7a76302d2.png)

I actually couldn't find php5-fpm in the Raspbian repositories (see below screenshot), so I'll admit to being stumped.
![pi2](https://user-images.githubusercontent.com/15352177/42401079-092404d0-8142-11e8-82e9-197dc96ed3d0.png)

You could try explicitly installing the package `php7.0-fpm` which would use the newer version of PHP, but if that doesn't work and php5-fpm works for you, then that should be fine. You'll just have to change the line in the guide from

`fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;`

to

`fastcgi_pass unix:/var/run/php/php5.0-fpm.sock;`

when editing the Nginx default site.

**Comment by riffleRock** [comment]
Sam, 

Thank you very much for the reply and info. I just received a new Raspberry Pi 3b+ in the mail, and I will try it. 

I really like the AirBeam 2 logger that you made and it is perfect for remote, rural sites where I am monitoring for coal ash particulates. 

As for the error, I don't know either why it happened. I thought that I ran all the updates for everything, but it was a Pi 2 and maybe something didn't load right. I'll return to that after I get my new Pi set up and running. If I run into more glitches, would you be willing to answer more questions? I will try not to flood you with trivial issues, but I am very anxious to get this working. I have done a lot of Python programming for many years, but not much with the Raspberry Pi board. 

Thanks again, 
John

**Comment by ShVerni** [comment]
Hi John,

I'd be more than happy to try and answer any questions you have. It should work on a Pi 2, but I haven't tested it so I don't know for sure. Either way, the Pi 2 doesn't have built-in Wi-Fi so going with the Pi 3 is a good idea.

Let me know how it goes, and good luck!

**Comment by ShVerni** [comment]
Hi John,

Just wanted to check-in if you'd had any progress?

**Comment by riffleRock** [comment]
Sam, 

Thank you for checking. Things are working well for logging, but I still have some access point steps to complete. I had some other work that took me away from the logger project, but hope to get back to it tomorrow. I'll be in touch. 

Thanks, 
John

**Comment by ShVerni** [comment]
Sounds good! In that case, I'm going to close this issue since php-fpm is working for you now. Please feel free to open another issue of you have one, or you can always send me an update via email as I'd love to hear about your progress.

Good luck!
