### ISSUE TITLE
No Device Connected; No such file or directory: '/dev/ttyACM0'

### ISSUE THREAD

**Issue by stopfortheklopp** [ShVerni/AirBeamLogger#2]
Hi, I was trying to set this Data Logger up as it would be of great help, but when I try to test it by running the command `sudo python3 data_logger.py` I get this error message:

```
sudo python3 data_logger.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_logger.py", line 18, in <module>
    timeout=1
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyAC
```
Also, when  accessing the Data Server from Chromium and clicking Start Data Logger, I get a prompt saying "No Device connected".

What am I missing
Any help would be greatly appreciated
Cheers

**Comment by stopfortheklopp** [comment]
For anyone wondering, the USB cable wasn't fully connected, that was the issue.

**Comment by sbdevarakonda** [comment]
Is the cable connecting the AirBeam to the raspberry Pi? Was it the issue? I am getting the same issue. Do we have to connect the AirBeam to the Pi using a cable?
