### ISSUE TITLE
New Firmware (3.7.19) does not log properly.

### ISSUE THREAD

**Issue by hairem** [ShVerni/AirBeamLogger#4]
I was using this to log output from an AriBeam2 to a raspberry pi but since they changed their firmware to 3.7.19 it doesn't work anymore. Any suggestions?

**Comment by ShVerni** [comment]
Hello,

What, specifically, isn't working? Is the AirBeam not connecting the the Pi, or is the data being produced corrupted in some way?

I haven't tried the new firmware, but I'll attempt to get my hands on one of ours to try it, but it might be while. In the meantime, check out our [troubleshooting](https://github.com/ShVerni/AirBeamLogger#troubleshooting), specifically try the last option. If there's no output it means AirCasting may have disabled or changed the serial output. If there is output, if you either post it here or send it to me and I can try to figure out if maybe they changed the format of the serial output.

**Comment by hairem** [comment]
I've tried the troubleshooting section already. When I try and change the data recorded to match the new format the loop breaks.

**Comment by hairem** [comment]
Here is the code that I edited:
```python
#!/usr/bin/env python
import time
import serial
import os
import shutil
import subprocess
import json
# Initialize variables.
timestr = time.strftime("%Y%m%d")
output_path = '/home/pi/AirBeam Output/output'+ timestr +'.csv'
server_path = '/var/www/html/output.csv'
config_path = '/home/pi/settings.json'
ser = serial.Serial(
    port='/dev/ttyACM1',
    baudrate = 9600,
    parity=serial.PARITY_NONE,
    stopbits=serial.STOPBITS_ONE,
    bytesize=serial.EIGHTBITS,
    timeout=1
)

# Grab and parse the settings.
settings = "";
with open(config_path, 'r') as settings_file:
    settings = json.load(settings_file);
if settings == "":
    print("Malformed settings file")
    exit(1)

counter = 0
delay = int(settings["delay"])
use_date = int(settings["date"])
use_ntp = int(settings["ntp"])
# Set initial date.
if (use_date == 1) and (use_ntp == 1):
    time.sleep(5)
    subprocess.call(['/home/pi/sync_time.sh'])
# Start measurement loop.
while 1:
    # Empty serial buffer.
    ser.flushInput()
    # Read data.
    x=ser.readline()
    # Parse data.
    data = x.decode('UTF-8').strip().split(' ')
    print(data)
    # Check for good data and output to file.
    if len(data) > 23 :
        with open(output_path, 'a') as output:
            if use_date == 1:
                output.write(time.strftime("%Y/%m/%d %H:%M " + "," + data[8] + "," + data[15] + "," + data[17] + "," + data[19] + "," + data[21] + "," + data[23] + "\r\n"))
            else:
                timepoint = (counter * delay) / 60
                output.write(str(timepoint) + "," + data[8] + "," + data[15] + "," + data[17] + "," + data[19] + "," + data[21] + "," + data[23] + "\r\n")
        # Copy output to server directory.
        shutil.copy(output_path, server_path)
    counter += 1
    # Syncy date and time via NTP every 24 hours if needed.
    if (use_date == 1) and (use_ntp == 1) and (counter * delay > 86400):
        counter = 0
        subprocess.call(['/home/pi/sync_time.sh'])
    time.sleep(60);
```

**Comment by ShVerni** [comment]
I don't see anything obviously wrong with your code, could you post the output from the AirBeam2 so I can compare it to how you're parsing it in your code?

**Comment by hairem** [comment]
raw output

> Temperature Counts 10 Plantower Counts 1 Airbeam2 MAC 001896100BD5 Firmware v3.7.19, 7 Sensor Parameter 87F 31C 304K 47RH PM1 0 PM2.5 0 PM10 0
Temperature Counts 10 Plantower Counts 1 Airbeam2 MAC 001896100BD5 Firmware v3.7.19, 7 Sensor Parameter 86F 30C 303K 47RH PM1 0 PM2.5 0 PM10 0
Temperature Counts 10 Plantower Counts 1 Airbeam2 MAC 001896100BD5 Firmware v3.7.19, 7 Sensor Parameter 86F 30C 303K 47RH PM1 0 PM2.5 0 PM10 0
Temperature Counts 10 Plantower Counts 2 Airbeam2 MAC 001896100BD5 Firmware v3.7.19, 7 Sensor Parameter 87F 31C 304K 47RH PM1 0 PM2.5 0 PM10 0

Edited output

> 2019/04/10 10:56 ,001896100BE3,29C,48RH,0,0,0

The issue is once I changed the Data[] output it stoped looping and only outputs once, butthe program keeps running.

**Comment by ShVerni** [comment]
I don't see an obvious reason why your code would only work once, but I admit I'm not very experienced with Python. Does it get to the `print(data)` line in the Python code, or does it just stop going through the loop altogether? You could add some `print()` statements to the loop to see which line things start to go wrong on. If it's still making it through the loop but not writing any data, maybe the line `if len(data) > 23` is causing it to skip writing the data.

If you go back to the old code will it still work? I know it won't log the correct data, but it should still log something and would tell you if it's a problem with your changes or something unrelated.

You could also try changing this line:

```
output.write(time.strftime("%Y/%m/%d %H:%M " + "," + data[8] + "," + data[15] + "," + data[17] + "," + data[19] + "," + data[21] + "," + data[23] + "\r\n"))
```
to this:
```
output.write(time.strftime("%Y/%m/%d %H:%M ") + "," + data[8] + "," + data[15] + "," + data[17] + "," + data[19] + "," + data[21] + "," + data[23] + "\r\n")
```

Although that shouldn't really make a difference.

All our AirBeams are currently deployed so I haven't had a chance to test the new update. Hopefully I can in the next couple of weeks.

**Comment by hairem** [comment]
Yeah I found that missing parenthesis, it was my fault I left it out, once I changed that it started working right, now I just need to power 3 Aribeams off one Raspberry pi. Sorry I bothered you over this since it was a mistake on my part.

**Comment by ShVerni** [comment]
No problem, I actually see that same parenthesis problem in my original code, even though it seemed to have worked until now, so I'm a bit flummoxed. Either way, I'll update my code to match and I'd like to use the serial communication logs you provided to further update my code to match the new firmware, so I appreciate you bringing this issue up.

If you have any further problems, or have any suggestions, please let me know.

**Comment by hairem** [comment]
Yeah feel free to use anything I posted here, if it helps. And again thanks for all the help sussing this out.

**Comment by ShVerni** [comment]
You're welcome, and good luck!
