### ISSUE TITLE
Airbeam not sending data to Pi

### ISSUE THREAD

**Issue by sbdevarakonda** [ShVerni/AirBeamLogger#5]
I was able to create an access point using the Pi and open the webpage pointing to 192.168.3.1. I can click on start and stop data logging, however, when I click on the Datafile, I get 404 not found message. Any advice is appreciated.  I have tried all the troubleshooting options suggested.

**Comment by ShVerni** [comment]
Hello,

So if the system says it successfully started the datalogger, be sure to wait the full timeout time for a the data file to be created, e.g. if you set your sampling interval to five minutes, you'll need to wait five minutes for the file to be written.

If that doesn't help, you can see what the Python script that is actually writing the data is doing by using SSH to connect the the Pi and in your home directory (`/home/pi/`) run the command `sudo python3 data_logger.py `

There may be some useful output if the script is crashing or otherwise unable to write the data file.

**Comment by sbdevarakonda** [comment]
Hi,
Thanks for your reply. The sampling interval is currently set to the default 5 sec (0.0833333).  I did run the command sudo python3 data_logger.py through the SSH terminal. The output is as below:
[' ']
[' ']
[' ']
[' ']
and it just continues like that. There is no data displayed.  I thought may be it's an issue with the port so I changed the port to ttyUSB0 and serial0 etc. But none of them worked.  I am still trying to figure it out.  Does the LED color change from red to some other color if it is connected to the Pi like when collecting data using a phone? Mine just stays blinking red.
Thanks.

**Comment by ShVerni** [comment]
It should just stay blinking read. So the script is reading the serial port but not receiving any data. I'd first try the suggestion laid out [here](https://github.com/ShVerni/AirBeamLogger/issues/3#issuecomment-477276458) which involves starting a mobile session again via the AirCAsting app. While you mention you've done this before, the AirBeam is a little touchy, so sometimes it will take a few tries to get it to work.

You can also verify which serial port is being used by first using the command `ls /dev/tty*` which will list all the serial ports on your system, you can then unplug the AirBeam from the Pi and run the command again as see if any of the ports disappear.

You can also try reading the port directly using `cat /dev/ttyACM0` or using that to read the port of your choice.

If none of that is revealing, then I suggest following the last step in the [troubleshooting ](https://github.com/ShVerni/AirBeamLogger#troubleshooting) section and hooking your AirBeam up to your computer and using PuTTY or the Arduino program's serial monitor to read the status messages from your AirBeam as it powers on. This will let you know if there are any hardware problems that may be interfering with the readings. For instance, I had the cellular module fail on one of my devices and it would hang on boot in the same manner you're describing. I had to disable the cellular module to get it working again, and even then it could take up to five minutes to get through the boot process and start reporting data. At the very least, you should be able to verify the AirBeam is putting out data properly, and can share that output here.

**Comment by sbdevarakonda** [comment]
Thanks for the suggestions. I will try them and will reply back with the updates. But, I am not sure how to connect the AirBeam directly through PuTTY. I am naive in this area, but I think an Host name or IP address is required to connect any device through PuTTY. I do not know what the address will be as the AirBeam is not connected to internet directly to get it's IP from the modem. I will appreciate your suggestion on this.

**Comment by ShVerni** [comment]
After plugging your AirBeam into your computer via USB, you can change the connection type in PuTTY to "Serial" below where you would enter the host name. Next you'll need to know which COM port your AirBeam is assigned, which you can look up in the Device Manager on Windows (it will be COM followed by a number, e.g. COM1)
![com](https://user-images.githubusercontent.com/15352177/75610519-d79fc380-5adf-11ea-9a4b-5ce1e69dcd32.jpeg)
In PuTTY you'll need to put that name where you'd normally enter the hostname, it should say "Serial line" when the "Serial" connection type is selected.
![PuTTY](https://user-images.githubusercontent.com/15352177/75610567-60b6fa80-5ae0-11ea-9599-b5b394f60087.PNG)

**Comment by sbdevarakonda** [comment]
Hi Sam,
Thanks for your help. I first tried to start the Mobile session multiple times and see if it works, but it did not. While the AirBeam is connected to Pi, if I start a mobile session it will display the data on the Putty terminal but does not save the data into the Pi. Then, I used the command `ls /dev/tty*` to see the port and it was the ttyACM0 which was disappearing when I disconnect the AirBeam. Next I used `cat /dev/ttyACM0` to see output.

![image](https://user-images.githubusercontent.com/51378104/75616262-f7091180-5b1c-11ea-8e5f-d0041b8e0661.png)

It stays like that for more than 15 minutes and does not say that the bluetooth is connected. Then, I connected AirBeam to the computer using the method you suggested and started it.

![image](https://user-images.githubusercontent.com/51378104/75616122-30d91880-5b1b-11ea-8b7c-8552c95214bf.png)

I started a Mobile session and it started displaying data

![image](https://user-images.githubusercontent.com/51378104/75616139-86adc080-5b1b-11ea-8cb3-d832a8666ac2.png)

I am assuming from this that AirBeam is probably working fine but I am still not getting an output.csv file.

![image](https://user-images.githubusercontent.com/51378104/75616167-dc826880-5b1b-11ea-8393-491fe46d6a13.png). 

I am not sure if something was not installed properly.

**Comment by ShVerni** [comment]
Hello,

So it looks like the AirBeam is not sending data over serial until you manually start a mobile session. What I think might be the problem is the firmware. Your firmware version is 11.5.18, the firmware I have on my AirBeams is 3.7.19. Confusingly, the firmware linked to from the [Habitat Map](https://www.habitatmap.org/blog/airbeam2-technical-specifications-operation-performance) is 3.19.18. Looking at the [AirCasting GitHub](https://github.com/HabitatMap/AirCastingAndroidClient/tree/master/arduino/aircasting) the most recently uploaded firmware is version 7.6.19 from four months ago, while your firmware was added 16 months ago.

Honestly, I can't figure out which is the latest firmware, or why they are all different.

So there are a couple of things you can do: You could try starting different sessions besides mobile, and see if the AirBeam will start spitting out data on its own over serial when you turn it on after a few minutes. Or I'd be happy to send you the firmware version I have if you want to flash your AirBeam with it. It's not terribly hard to too, but I can't promise it will work since I don't know if there are any hardware revisions, although I think that's unlikely. We could also try to modify the firmware version you have to output the data over serial, but that might take a while to figure out.

You could also contact [Habitat Map](mailto:info@habitatmap.org) and see if they can clear up the firmware question, or let you know if it would be okay to install the 3.7.19 firmware I have. They may even be able to suggest how to get the AirBeam to automatically output the data via serial like it does in firmware 3.7.19 without any major modifications.

**Comment by sbdevarakonda** [comment]
I would be happy to flash the firmware you have if you can send it to me. I would be grateful if you can give me directions on how to flash. Thanks for all your help.

**Comment by ShVerni** [comment]
You can find a link to download the Arduino IDE and the firmware I have [here](https://1drv.ms/u/s!AiUvDVihabhnjI55bw_rihX4N7kltw?e=YIecXG), note that the link will only be live for one week from this posting date.

For instructions, here is a summary of the ones I received from Habitat Map:

> 1) Plug the AirBeam2 into your computer and turn it on.
> 
> 2) Launch the Arduino IDE and use the Arduino IDE 1.0.5-r3 to open the firmware by navigating to File > Open.
> 
> 3) Via the Arduino IDE navigate Tools > Board and select [BootloaderCDC]AT90USB1286.
> 
> 4) Note the COM ports listed in Arduino by navigating to Tools > Serial Port.
> 
> 5) Remove the three AB2 screws and open the enclosure.
> 
> 6) Turn on the AB2 and connect it to the PC via the USB cable. Navigate to Tools > Serial Port and note the COM port associated with the AB2, this is the AB2 "run mode" COM port.
> 
> 7) With the board oriented so the small metal box is nearest you, press and hold down the left button, then press and hold down the right button. Hold both buttons for 5 seconds, then release the right button, then release the left button. Once you've done this there will be another COM port associated with the AB2, this is the AB2 "reprogramming mode" COM port. Select the "reprogramming mode" COM port in the Arduino IDE by navigating to Tools > Serial Port.
> 
> 8) To upload the firmware navigate to File > Upload or click the right facing arrow.
> 
> 9) When programming has finished, power off the AB2 for 5 seconds then power it back on. Your unit is now reprogrammed with the updated firmware. You can now select the COM port associated with the AB2 "run mode" to see detailed information on the firmware you have uploaded.

A few things to note: this firmware may be the version I updated to disable the cellular modem checks after it failed, so if that's a problem I can see if I can reverse that. As mentioned previously, I can't promise this firmware will work on your particular AirBeam2, and there is always the small chance of bricking something when updating the firmware, **so proceed at your own risk**.

Good luck!

**Comment by sbdevarakonda** [comment]
Hi,
I contacted HabitatMap and was able to update it to the latest firmware. The data logging is working now. It was the firmware. Thanks for all your help. I am logging the data now with 5 second, would it be possible to do a lower time interval like 1 sec. I reduced the time to 1 and 2 sec but it would output data with 6 second interval for some reason. 
Thanks again.

**Comment by ShVerni** [comment]
I'm glad to hear the issue with data output was resolved.

As for the time problem, there are a few possibilities: First, the script can't log data any faster than the AirBeam2 spits it out over serial, so if it only outputs data every 2 or 3 seconds the serial connection won't have any data for it to read and will timeout, which will start the whole loop over and actually take up more time than if it had waited longer in the first place. There is also the chance that the data read from the AirBeam2 can't be parsed correctly, so the script will try again after a 0.1 second pause, which can cause delays as well.

I would start by using PuTTY or another program to monitor the output rate from the AirBeam, how long it takes to output each line is the absolute minimum time it needs between reads.

I'll admit the script isn't really optimized for very fast reads, and I'm not much good with Python beyond the basics, so there is probably room to improve performance on the script. If you do figure out howto get faster reads from the data_logger.py script, let me know and hopefully I can add or update the script with your improvements.
